ALTER TABLE `outlet` ADD COLUMN `Status` TINYINT(4) DEFAULT NULL;
ALTER TABLE `outlet` ADD COLUMN `HouseNumber` VARCHAR(45) DEFAULT NULL;
ALTER TABLE `outlet` ADD COLUMN `ProvinceID` BIGINT(20) DEFAULT NULL ;
ALTER TABLE `outlet` ADD COLUMN `Telephone` VARCHAR(45) DEFAULT NULL