ALTER TABLE `answer` DROP FOREIGN KEY `FK_Answer_AskID`;

ALTER TABLE `answer` ADD CONSTRAINT `FK_Answer_AskID` FOREIGN KEY (`AskID`) REFERENCES `ask` (`AskID`) ON DELETE CASCADE ON UPDATE CASCADE;


ALTER TABLE `ask` DROP FOREIGN KEY `FK_Ask_ClassRoster`;

ALTER TABLE `ask` ADD CONSTRAINT `FK_Ask_ClassRoster` FOREIGN KEY (`ClassRosterID`) REFERENCES `classroster` (`ClassRosterID`) ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE `ask` DROP FOREIGN KEY `FK_Ask_AskerID`;

ALTER TABLE `ask` ADD CONSTRAINT `FK_Ask_AskerID` FOREIGN KEY (`AskerID`) REFERENCES `user` (`UserID`) ON DELETE CASCADE ON UPDATE CASCADE;

