DROP TABLE IF EXISTS `ask`;
CREATE TABLE `ask` (
  `AskID` BIGINT(11) NOT NULL AUTO_INCREMENT,
  `Title` VARCHAR(125) DEFAULT NULL,
  `AskContent` LONGTEXT DEFAULT NULL,
  `AskerID` BIGINT(11) DEFAULT NULL,
  `Status` TINYINT(4) DEFAULT NULL,
  `AskDate` DATETIME DEFAULT NULL,
  PRIMARY KEY (`AskID`),
	CONSTRAINT `FK_Ask_AskerID` FOREIGN KEY (`AskerID`) REFERENCES `User` (`UserID`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=INNODB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

DROP TABLE IF EXISTS `answer`;
CREATE TABLE `answer` (
  `AnswerID` BIGINT(11) NOT NULL AUTO_INCREMENT,
  `AskID` BIGINT(11) DEFAULT NULL,  
  `AnswerContent` LONGTEXT DEFAULT NULL,
  `RespondentID` BIGINT(11) DEFAULT NULL,
  `AnswerDate` DATETIME DEFAULT NULL,
  PRIMARY KEY (`AnswerID`),
	CONSTRAINT `FK_Answer_AskID` FOREIGN KEY (`AskID`) REFERENCES `Ask` (`AskID`) ON DELETE NO ACTION ON UPDATE NO ACTION,
	CONSTRAINT `FK_Answer_RespondentID` FOREIGN KEY (`RespondentID`) REFERENCES `User` (`UserID`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=INNODB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;


ALTER TABLE `fcvnew`.`ask`

ADD COLUMN `ClassRosterID` BIGINT NULL DEFAULT NULL  AFTER `AskDate` ,

 ADD CONSTRAINT `FK_Ask_ClassRoster`
  FOREIGN KEY (`ClassRosterID` )
  REFERENCES `fcvnew`.`classroster` (`ClassRosterID` )
  ON DELETE CASCADE
  ON UPDATE CASCADE
,
ADD INDEX `FK_Ask_ClassRoster_idx` (`ClassRosterID` ASC) ;


