DROP TABLE IF EXISTS `OutletRoute`;
CREATE TABLE `OutletRoute` (
  `OutletRouteID` BIGINT(11) NOT NULL AUTO_INCREMENT,
  `OutletID` BIGINT(11) DEFAULT NULL,
  `UserID` BIGINT(11) DEFAULT NULL,
  `Thu 2` CHAR DEFAULT NULL,
  `Thu 3` CHAR DEFAULT NULL,
  `Thu 4` CHAR DEFAULT NULL,
  `Thu 5` CHAR DEFAULT NULL,
  `Thu 6` CHAR DEFAULT NULL,
  `Thu 7` CHAR DEFAULT NULL,
  PRIMARY KEY (`OutletRouteID`),
	CONSTRAINT `FK_OutletRoute_OutletID` FOREIGN KEY (`OutletID`) REFERENCES `Outlet` (`OutletID`) ON DELETE NO ACTION ON UPDATE NO ACTION,
	CONSTRAINT `FK_OutletRoute_UserID` FOREIGN KEY (`UserID`) REFERENCES `User` (`UserID`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=INNODB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;