DROP TABLE IF EXISTS `OutletRoot`;
CREATE TABLE `OutletRoot` (
  `OutletRootID` BIGINT(11) NOT NULL AUTO_INCREMENT,
  `OutletID` BIGINT(11) DEFAULT NULL,
  `UserID` BIGINT(11) DEFAULT NULL,
  `2` INT DEFAULT NULL,
  `3` INT DEFAULT NULL,
  `4` INT DEFAULT NULL,
  `5` INT DEFAULT NULL,
  `6` INT DEFAULT NULL,
	`7` INT DEFAULT NULL,
  PRIMARY KEY (`OutletRootID`),
	CONSTRAINT `FK_OutletRoot_OutletID` FOREIGN KEY (`OutletID`) REFERENCES `Outlet` (`OutletID`) ON DELETE NO ACTION ON UPDATE NO ACTION,
	CONSTRAINT `FK_OutletRoot_UserID` FOREIGN KEY (`UserID`) REFERENCES `User` (`UserID`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=INNODB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;